name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'build'
      - .git


jobs:
  Build_the_markup_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install ruby dependencies
        run: bundle install
      - name: Build static site
        run: bundle exec middleman build  
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /build/*
          key: ${{ runner.os }}-files-${{ hashFiles('/build/**') }}
          
          
  Deploy_the_markup_files:
    needs: Build_the_markup_files
    runs-on: ubuntu-latest
    steps:      
       - name: checkout destination
         run: |       
             git clone https://github.com/P0C-demo/P0C-demo.github.io.git   
       - name: Retrieve cached files
         uses: actions/cache@v2
         with:
           path: /build/
           key: ${{ runner.os }}-files-${{ hashFiles('build/**') }}
       
       - name: List files
         run: | 
              cd dest/P0C-demo-github.io
              ls
       - name: Commit
         run: |
             cd dest/P0C-demo.github.io
             ls
             git config user.name "Github.Action"
             git config user.email "deliverablestangible@gmail.com"
             git add .
             git commit -m "Deploy to GitHub Pages"
             echo '=>'
             echo ${{ secrets.PAT }}
             echo '<='
             git push https://${{ secrets.PAT }}@github.com/P0C-demo/P0C-demo.github.io.git
