name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: make checkout folder for source
        run: |
           mkdir src && cd src   
           git clone https://github.com/abigailjhouston/income-tax-mtd-end-to-end-service-guide.git
      - name: checkout destination
        run: |
           mkdir dest && cd dest
           git clone https://github.com/abigailjhouston/abigailjhouston.github.io.git   
      - name: copy and commit
        run: |         
           cp -r src/income-tax-mtd-end-to-end-service-guide/build/*  dest/abigailjhouston.github.io/
      - name: Commit
        run: |
           cd dest/abigailjhouston.github.io
           ls
           git config user.name "Github.Action"
           git config user.email "abigail.houston@gmail.com"
           git add .
           git commit -m "Deploy to GitHub Pages"
           git push https://${{ secrets.PAT }}@github.com/abigailjhouston/abigailjhouston.github.io.git
