- name: Copy files to another repository
  uses: nkoppel/push-files-to-another-repository@v1.1.1
  env:
    API_TOKEN_GITHUB: ${{ secrets.PAT }}
  with:
    source-files: '/build/'
    destination-username: 'abigailjhouston'
    destination-repository: 'abigailjhouston.github.io'
    destination-directory: '/'
    commit-email: 'abigail.houston@gmail.com'
