- name: Copy files to another repository
  uses: nkoppel/push-files-to-another-repository@v1.1.1
env:
  API_TOKEN_GITHUB: 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
with:
  source-files: 'webpage/'
  destination-username: 'abigailjhouston'
  destination-repository: 'abigailjhouston.github.io'
  destination-directory: '/'
  commit-email: 'abigail.houston@gmail.com'
