name: Copy files to another repository
on: push
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT }}
      with:
        source_folder: 'build'
        destination_repo: 'abigailjhouston.github.io'
        destination_folder: '/'
        user_email: 'abigail.houston@gmail.com'
        user_name: 'abigailjhouston'
        commit_msg: 'Updated build'
