name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: make checkout folder for source
        run: |
           mkdir src && cd src
           cd ..
        
      - name: Checkout source
        uses: actions/checkout@v2
        
      - name: make checkout folder for destination
        run: |
           mkdir dest && cd dest
           git clone https://github.com/abigailjhouston/abigailjhouston.github.io.git
           cd ..
                      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cd src
          cp -avr /build/ ../dest/
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
